### ISSUE TITLE
Asterisk  (*) not showing up in training tickets

### ISSUE THREAD

**Issue by jackson-smith-ZDC** [vZDC-ARTCC/website#16]
### Your Vatsim CID

1471203

### Description

When writing a ticket, I attempted to put examples of a STARS point out in the ticket, and when I typed an asterisk * it does now show up in the submitted ticket. 

### Minimal Reproduction

<HANDOFF ID> <*> <SLEW TARGET>

### Additional info

Ticket link - https://vzdc.org/training/sessions/cly90ss39021ed8lphy3xcyvz
Lesson 3-2-SV for Leo Roberts (1560689)

### Validation

- [X] I have searched open/closed issues and did not find any similar bugs

**Comment by harryxu2626** [comment]
Asterisks are a special character in Markdown formatting. Specifically in this case, one asterisk is used to format italics (https://www.markdownguide.org/basic-syntax/#italic). For now, to escape the asterisk as a special character, put a backslash ("\") in front of the asterisk so that it'll render normally (e.g. "<HANDOFF ID> <\*> <SLEW TARGET>")

In an upcoming build, we're adding the simplified text editor when creating/editing tickets, and we'll work on a way to toggle Markdown vs. non-Markdown rendering when reading the tickets.

**Comment by harryxu2626** [comment]
Workarounds have been implement on the trainer and trainee side of the tickets. Further enhancements expected in the future to link the mode selected by the trainer (Markdown vs. non-Markdown) to the ticket so that the trainee does not have to manually select Markdown vs. non-Markdown.
